# Generated by Django 5.2.7 on 2025-11-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom complet du participant', max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(help_text='Adresse email (doit être unique)', max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(help_text='Numéro de téléphone', max_length=20, verbose_name='Téléphone')),
                ('institution', models.CharField(blank=True, help_text="Établissement d'étude (pour étudiants)", max_length=200, null=True, verbose_name='Établissement')),
                ('registration_type', models.CharField(choices=[('etudiant', 'Étudiant'), ('partenaire', 'Partenaire'), ('sponsor', 'Sponsor')], default='etudiant', max_length=20, verbose_name="Type d'inscription")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Inscription à l'événement",
                'verbose_name_plural': "Inscriptions à l'événement",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='events_even_created_9d0c69_idx'), models.Index(fields=['email'], name='events_even_email_87537a_idx')],
            },
        ),
    ]
